### PR TITLE
Fix ConfigMap glitches and doc registry caching

### LINKED ISSUE #31: Document how to set up a local/private registry for caching
**Describe the problem/challenge you have**
BuildKit has powerful caching constructs which can be utilized to speed up incremental builds on a multi-node environment.  For these to work well, you need a registry running "close" to the builder with high bandwidth and low latency.  This should be easily achievable with a local private registry running inside the same namespace where the builders run.

**Description of the solution you'd like**

Write a doc, likely including kube-yaml files in the tree that shows how developers can easily spin up a local registry instance inside the cluster, with a Service so the builders can access it directly for caching purposes.  The open source https://github.com/docker/distribution registry should be sufficient for developer use.  The registry should not be exposed externally.  The docs can be written to pull the yaml directly from this repo (e.g. `kubectl apply -f https://raw.githubusercontent.com/vmware-tanzu/buildkit-cli-for-kubectl/main/examples/local-registry.yaml`). Those docs should then show how to pass the right flags to `kubectl build ...` to leverage that local cache (`--cache-*`) with a "well known" Service name matching the yaml definition (perhaps something like `buildkit-cache`)

**Design/Architecture Details**

TBD

**Environment Details:**

- kubectl buildkit version (use `kubectl buildkit version`)

v0.1.0

- Kubernetes version (use `kubectl version`)

NA

- Where are you running kubernetes (e.g., bare metal, vSphere Tanzu, Cloud Provider xKS, etc.)

NA

- Container Runtime and version (e.g. containerd `sudo ctr version` or dockerd `docker version` on one of your kubernetes worker nodes)

NA

**Vote on this request**

This is an invitation to the community to vote on issues.  Use the "smiley face" up to the right of this comment to vote.

- :+1: "This project will be more useful if this feature were added"
- :-1: "This feature will not enhance the project in a meaningful way"

### PR DESCRIPTION
**Pull request by dhiltgen**
This fixes a few corner cases in how we handle ConfigMaps for the
buildkitd toml config file.  It adds integration coverage for those
scenarios.  It also adds a brief example showing how to configure
a local registry for caching purposes to speed up incremental
builds on a multi-node cluster.

Closes #31

### CODE REVIEW

File: pkg/driver/kubernetes/driver.go [hunk 1]
```diff
@@ -69,21 +70,27 @@ type Driver struct {
...
 	loadbalance          string
 	authHintMessage      string
 }
 
 func (d *Driver) Bootstrap(ctx context.Context, l progress.Logger) error {
 	return progress.Wrap("[internal] booting buildkit", l, func(sub progress.SubLogger) error {
-
 		_, err := d.configMapClient.Get(ctx, d.configMap.Name, metav1.GetOptions{})
+
 		if err != nil {
```
Comment (pdevine) [inline pkg/driver/kubernetes/driver.go:83]: It's a little unclear to me how this works. What happens if a serious error is passed back here but userSpecifiedConfig is set?

File: CONTRIBUTING.md [hunk 2]
```diff
@@ -35,6 +35,11 @@ Assuming you have a valid kube configuration pointed at a cluster, you can run t
 make integration
 ```
 
+If you want to run a single suite of tests while working on a specific area of the tests or main code, use something like this:
+```
+make integration EXTRA_GO_TEST_FLAGS="-run TestConfigMapSuite -v"
```
[the remark this answers is not in the document]
Comment (dhiltgen) [reply CONTRIBUTING.md:40]: I'll add a hint to find them

File: pkg/driver/kubernetes/driver.go (hunk 1 above)
Comment (dhiltgen) [reply pkg/driver/kubernetes/driver.go:83]: Good point - it would probably be masked - let me refine this a tad more to validate the error specifically.

**Review by pdevine — APPROVED** [review]
