### PR TITLE
Harden default creation for parallel invocation

### LINKED ISSUE #55: Parallel builds without a builder created result in error
**What steps did you take and what happened**
A repro can be found in vmware-tanzu/carvel-kbld#69

Steps:
1. Clean kind cluster
```shell
$ kubectl buildkit ls
NAME     NODE                      DRIVER     STATUS PLATFORMS
```
2. using `kbld` to create 2 images. Next is the configuration file we use that specifies the usage of buildkit to create 2 images from 2 different paths. the path for this specific application can be found: https://github.com/vmware-tanzu/carvel-kbld/tree/develop/test/e2e/
```
kind: Object
spec:
- image: simple-app-two
- image: simple-app-three
---
apiVersion: kbld.k14s.io/v1alpha1
kind: Sources
sources:
- image: simple-app-two
  path: assets/simple-app
  kubectlBuildkit:
    build:
      file: dev/Dockerfile.dev
- image: simple-app-three
  path: assets/simple-app
  kubectlBuildkit:
    build:
      target: build-env
```
3. the command to used to run is: `kbld -f repro.yml --images-annotation=false`
4. the result is:
```
simple-app-three | starting build (using kubectl buildkit): assets/simple-app -> kbld:rand-1605907729199009000-163181625647-simple-app-three
simple-app-two | starting build (using kubectl buildkit): assets/simple-app -> kbld:rand-1605907729199007000-21210716319629-simple-app-two
simple-app-three | #1 [internal] booting buildkit
simple-app-two | #1 [internal] booting buildkit
simple-app-three | #1 ERROR: error while calling configMap.Create for "buildkit": configmaps "buildkit" already exists
simple-app-three | ------
simple-app-three |  > [internal] booting buildkit:
simple-app-three | ------
simple-app-three | Error: error while calling configMap.Create for "buildkit": configmaps "buildkit" already exists
simple-app-three | error: exit status 1
simple-app-three | finished build (using kubectl buildkit)
```

**What did you expect to happen**
I expect the CLI to be able to wait for the builder to be created and not error out

**Environment Details:**

- kubectl buildkit version: refs/tags/v0.1.0
- Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T21:54:15Z", GoVersion:"go1.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Using `kind` to run k8s
- Using docker version 19.03.13

**Vote on this request**

This is an invitation to the community to vote on issues.  Use the "smiley face" up to the right of this comment to vote.

- :+1: "I would like to see this bug fixed as soon as possible"
- :-1: "There are more important bugs to focus on right now"

### PR DESCRIPTION
**Pull request by dhiltgen**
If multiple build commands are run in parallel without a builder already
existing, there are race conditions where those default creations can
get confused and cause builds to fail
This adds a new test case to verify parallel builds work, and hardens
the bootstrapping code to detect "already exists" errors and retry

Closes #55

### CODE REVIEW

File: pkg/driver/driver.go [hunk 1]
```diff
@@ -98,14 +100,19 @@ func Boot(ctx context.Context, d Driver, pw progress.Writer) (*client.Client, st
 		}
 		try++
 		if info.Status != Running {
-			if try > 2 {
+			if try > 3 {
```
Comment (pdevine) [inline pkg/driver/driver.go:103]: maybe stick this in a constant?

File: pkg/driver/driver.go [hunk 2]
```diff
@@ -98,14 +100,19 @@ func Boot(ctx context.Context, d Driver, pw progress.Writer) (*client.Client, st
...
 			}
 			if err := d.Bootstrap(ctx, func(s *client.SolveStatus) {
 				if pw != nil {
 					pw.Status() <- s
 				}
-			}); err != nil {
+			}); err != nil && (strings.Contains(err.Error(), "already exists") || strings.Contains(err.Error(), "not found")) {
+				// This most likely means another build is running in parallel
+				// Give it just enough time to finish creating resources then retry
+				time.Sleep(250 * time.Millisecond)
```
Comment (pdevine) [inline pkg/driver/driver.go:113]: will this always complete in <1s (i.e. 3 attempts w/ 250ms sleeps per attempt)?

Comment (dhiltgen) [reply pkg/driver/driver.go:113]: Not necessarily.  The new retry wont add more than 1s, but bootstrapping the builder when things are working properly can take far longer if you have to pull images, etc.

**Review by pdevine — APPROVED** [review]
